// LOGIN USER
export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const LOGOUT = 'USERS_LOGOUT';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const PUT_USER_DATA = 'PUT_USER_DATA';
export const POST_USER_DATA = 'POST_USER_DATA';
export const FETCH_INSTITUICAO_DATA = 'FETCH_INSTITUICAO_DATA';
export const FETCH_INSTITUICAO_FAILED = 'FETCH_INSTITUICAO_FAILED';
